---
- name: Update Docker Compose services
  hosts: docker_immich
  gather_facts: no
  vars:
    docker_dir: /docker
  tasks:
  
    - name: Pull images
      community.docker.docker_compose_v2_pull:
        project_src: [docker_dir]
      register: output_pull

    - name: Show results
      ansible.builtin.debug:
        var: output_pull

    - name: Run `docker compose up`
      community.docker.docker_compose_v2:
        project_src: [docker_dir]
      register: output_up

    - name: Show results
      ansible.builtin.debug:
        var: output_up

    - name: Prune Image
      community.docker.docker_prune:
        images: true
      register: output_prune

    - name: Show results
      ansible.builtin.debug:
        var: output_prune
